# -*- coding: utf-8 -*-
"""Guessing Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9ZJ-EMdGKZEP-RJGXx8f_kNlzVP-ibb
"""

import random

print("🎯 Welcome to the Number Guessing Game!")
print("I'm thinking of a number between 1 and 100.")

# Generate random number
secret_number = random.randint(1, 100)
attempts = 0

while True:
    try:
        # Take input from user
        guess = int(input("\nEnter your guess: "))
        attempts += 1

        # Compare with secret number
        if guess < secret_number:
            print("Too low! Try again.")
        elif guess > secret_number:
            print("Too high! Try again.")
        else:
            print(f"🎉 Congratulations! You guessed it right in {attempts} attempts.")
            break

    except ValueError:
        print("Invalid input! Please enter an integer only.")

