# -*- coding: utf-8 -*-
"""To Do List Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Br00L1XhcLGVOHhhkhTgLUWQ6N89z8Fk
"""

# Task 3: To-Do List Manager

# File to store tasks
TASK_FILE = "tasks.txt"

# Function to load tasks from file
def load_tasks():
    try:
        with open(TASK_FILE, "r") as file:
            tasks = [line.strip() for line in file.readlines()]
        return tasks
    except FileNotFoundError:
        return []

# Function to save tasks to file
def save_tasks(tasks):
    with open(TASK_FILE, "w") as file:
        for task in tasks:
            file.write(task + "\n")

# Function to display tasks
def display_tasks(tasks):
    if not tasks:
        print("\n📌 No tasks found!")
    else:
        print("\n📝 Your To-Do List:")
        for i, task in enumerate(tasks, start=1):
            print(f"{i}. {task}")

# Function to add a task
def add_task(tasks):
    task = input("\nEnter new task: ")
    tasks.append(task + " [ ]")  # [ ] means not completed
    save_tasks(tasks)
    print("✅ Task added successfully!")

# Function to delete a task
def delete_task(tasks):
    display_tasks(tasks)
    try:
        choice = int(input("\nEnter task number to delete: "))
        removed = tasks.pop(choice - 1)
        save_tasks(tasks)
        print(f"🗑️ Task '{removed}' deleted.")
    except (ValueError, IndexError):
        print("❌ Invalid choice!")

# Function to mark a task as completed
def mark_completed(tasks):
    display_tasks(tasks)
    try:
        choice = int(input("\nEnter task number to mark as completed: "))
        if "[x]" in tasks[choice - 1]:
            print("⚠️ Task already completed!")
        else:
            tasks[choice - 1] = tasks[choice - 1].replace("[ ]", "[x]")
            save_tasks(tasks)
            print("🎉 Task marked as completed!")
    except (ValueError, IndexError):
        print("❌ Invalid choice!")

# Main program
def main():
    tasks = load_tasks()
    while True:
        print("\n====== TO-DO LIST MANAGER ======")
        print("1. View tasks")
        print("2. Add task")
        print("3. Delete task")
        print("4. Mark task as completed")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == "1":
            display_tasks(tasks)
        elif choice == "2":
            add_task(tasks)
        elif choice == "3":
            delete_task(tasks)
        elif choice == "4":
            mark_completed(tasks)
        elif choice == "5":
            print("👋 Exiting To-Do List Manager. Goodbye!")
            break
        else:
            print("❌ Invalid choice, please try again!")

if __name__ == "__main__":
    main()

