# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jzQaZHKwFBrtffpl6cjP1fUbfcgQ3CeG
"""

# Task 1: Build Calculator

# Functions for operations
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    try:
        return x / y
    except ZeroDivisionError:
        return "Error: Division by zero is not allowed."

print("Welcome to Command-Line Calculator!")
print("Available operations: + , - , * , /")

while True:
    try:
        # Taking inputs
        num1 = float(input("\nEnter first number: "))
        operator = input("Enter operator (+, -, *, /): ")
        num2 = float(input("Enter second number: "))

        # Performing operation
        if operator == "+":
            result = add(num1, num2)
        elif operator == "-":
            result = subtract(num1, num2)
        elif operator == "*":
            result = multiply(num1, num2)
        elif operator == "/":
            result = divide(num1, num2)
        else:
            print("Invalid operator! Please use +, -, *, or /.")
            continue

        # Display result
        print(f"Result: {num1} {operator} {num2} = {result}")

    except ValueError:
        print("Invalid input! Please enter numeric values only.")

    # Exit option
    choice = input("\nDo you want to perform another calculation? (yes/no): ").lower()
    if choice != "yes":
        print("Exiting Calculator. Goodbye!")
        break

